{
  "hash": "f89e144841b5d62cc35846bf7e5ebd2b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Formulasi Susu Ibu Hamil: Pendekatan *Complete Diet* Bertahap\"\nsubtitle: \"Diadaptasi dari metode formulasi pakan (Chiba, *Animal Nutrition Handbook*, Section 18)\"\noutput:\n  html_document:\n    toc: true\n    toc_float: true\n    number_sections: true\n    df_print: kable\neditor_options: \n  markdown: \n    wrap: 72\n---\n\n\n\n## Tujuan dan catatan penting\n\nDi materi kuliah, contoh *Formulating a Complete Diet* memakai kasus\nuntuk pakan babi *grower-finisher*, dimana protein diseimbangkan\nterlebih dulu, lalu disusul oleh fosfor, kalsium, dan terakhir protein\ndikoreksi lagi. Pada perhitungan ini, **logika yang sama** dipakai untuk\nmerancang **susu bubuk ibu hamil**.\n\nHal yang akan dipelajari:\n\n1.  Menyusun **spesifikasi** (target zat gizi) dan **daftar bahan**.\n2.  Menyeimbangkan zat gizi **satu per satu** dengan persamaan aljabar\n    satu variabel.\n3.  Memahami kenapa perlu **koreksi ulang**, dan bagaimana **iterasi**\n    atau **sistem persamaan linear** menyelesaikannya sekaligus.\n4.  Menghitung nilai gizi lengkap, basis kering, takaran saji, dan\n    **premix** vitamin-mineral.\n\n> **Penting:** Semua angka komposisi bahan dan target di dokumen ini\n> adalah **angka hipotetis untuk latihan**, bukan resep produk\n> sungguhan. Formulasi nyata memerlukan data analisis laboratorium\n> setiap lot bahan, uji stabilitas, uji sensori, dan kepatuhan terhadap\n> regulasi BPOM.\n\n**Cara pakai:** jalankan setiap *chunk* secara berurutan (tombol ▶ di\nRStudio), baca penjelasannya, lalu cocokkan hasilnya dengan hitungan\nmanual di kertas. Dokumen ini hanya memakai *library base* R dan\n*library* `knitr`.\n\n## Langkah 0: Data bahan dan target\n\n### Komposisi bahan\n\nMasukkan semua angka dalam **gram per 100 g bahan, basis basah**,\nkecuali dinyatakan lain. Dalam contoh kasus ini, susu bubuk ibu hamil\nyang akan dibuat menggunakan 7 buah bahan sesuai dengan data `nama`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbahan <- data.frame(\n  kode    = c(\"skim\", \"malto\", \"lemak\", \"caco3\", \"fos\", \"dha\", \"premix\"),\n  nama    = c(\"Susu skim bubuk\", \"Maltodekstrin\", \"Bubuk lemak nabati (70% lemak)\",\n              \"Kalsium karbonat\", \"FOS-inulin\", \"Bubuk DHA (mikroenkapsulasi)\",\n              \"Premix vitamin-mineral\"),\n  air     = c(4,    5,  2,    0,  5,  3, 0),\n  protein = c(34,   0,  3,    0,  0, 10, 0),\n  lemak   = c(1,    0,  70,   0,  0, 45, 0),\n  karbo   = c(52,   95, 23,   0,  0, 40, 0),   # karbohidrat tercerna (laktosa, dll.)\n  serat   = c(0,    0,  0,    0, 95,  0, 0),   # serat pangan (FOS-inulin)\n  Ca      = c(1.25, 0,  0.02, 40, 0,  0, 0)    # g Ca per 100 g bahan\n)\nrownames(bahan) <- bahan$kode\nbahan\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"kode\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"nama\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"air\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"protein\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"lemak\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"karbo\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"serat\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Ca\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"skim\",\"2\":\"Susu skim bubuk\",\"3\":\"4\",\"4\":\"34\",\"5\":\"1\",\"6\":\"52\",\"7\":\"0\",\"8\":\"1.25\",\"_rn_\":\"skim\"},{\"1\":\"malto\",\"2\":\"Maltodekstrin\",\"3\":\"5\",\"4\":\"0\",\"5\":\"0\",\"6\":\"95\",\"7\":\"0\",\"8\":\"0.00\",\"_rn_\":\"malto\"},{\"1\":\"lemak\",\"2\":\"Bubuk lemak nabati (70% lemak)\",\"3\":\"2\",\"4\":\"3\",\"5\":\"70\",\"6\":\"23\",\"7\":\"0\",\"8\":\"0.02\",\"_rn_\":\"lemak\"},{\"1\":\"caco3\",\"2\":\"Kalsium karbonat\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"40.00\",\"_rn_\":\"caco3\"},{\"1\":\"fos\",\"2\":\"FOS-inulin\",\"3\":\"5\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"95\",\"8\":\"0.00\",\"_rn_\":\"fos\"},{\"1\":\"dha\",\"2\":\"Bubuk DHA (mikroenkapsulasi)\",\"3\":\"3\",\"4\":\"10\",\"5\":\"45\",\"6\":\"40\",\"7\":\"0\",\"8\":\"0.00\",\"_rn_\":\"dha\"},{\"1\":\"premix\",\"2\":\"Premix vitamin-mineral\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0.00\",\"_rn_\":\"premix\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nPenjelasan singkat tiap bahan:\n\n| Bahan susu ibu hamil | Peran |\n|----|----|\n| Susu skim bubuk | Sumber protein utama (dan kalsium) |\n| Maltodekstrin | Sumber energi dan sebagai **bahan \"pengisi/penyesuai\"** |\n| Bubuk lemak nabati | Sumber lemak |\n| Kalsium karbonat | Sumber kalsium murni |\n| FOS-inulin, bubuk DHA, premix | **Bahan tetap** dengan jumlah yang sudah diputuskan |\n\nMaltodekstrin berperan seperti jagung pada pakan babi: setiap kali bahan\nlain ditambah, **maltodekstrin yang dikurangi** supaya total tetap 100\ng.\n\nAsumsi yang sama seperti di buku: **premix dianggap tidak menyumbang\nprotein, lemak, maupun kalsium** (kontribusinya terlalu kecil). Isi\npremix dirancang terpisah di bagian terakhir.\n\n### Target spesifikasi\n\nTarget per **100 g bubuk** (basis basah):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntarget <- c(protein = 22,   # g/100 g\n            lemak   = 8,    # g/100 g\n            Ca      = 1.1)  # g/100 g  (= 1.100 mg/100 g)\ntarget\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> protein   lemak      Ca \n#>    22.0     8.0     1.1\n```\n\n\n:::\n:::\n\n\n### Bahan tetap (*fixed ingredients*)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntetap <- c(fos = 3, dha = 1, premix = 1)   # g per 100 g formula\nsisa  <- 100 - sum(tetap)\nsisa\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 95\n```\n\n\n:::\n:::\n\n\n**Maksudnya:** jumlah FOS-inulin, bubuk DHA, dan premix sudah diputuskan\ndi awal (misalnya berdasarkan dosis prebiotik dan target DHA). Jadi\nhanya **95 g** yang tersisa untuk dibagi ke susu skim,\nmaltodekstrin, bubuk lemak, dan kalsium karbonat.\n\nFungsi untuk menghitung isi gizi sebuah resep\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# resep: vektor bernama, satuan g bahan per 100 g formula\nhitung_gizi <- function(resep, kolom = c(\"air\", \"protein\", \"lemak\", \"karbo\", \"serat\", \"Ca\")) {\n  komposisi <- as.matrix(bahan[names(resep), kolom])\n  colSums(komposisi * resep / 100)   # gram zat gizi per 100 g formula\n}\n```\n:::\n\n\n**Maksudnya:** untuk setiap zat gizi, kontribusi sebuah bahan = *jumlah\nbahan × kadar zat gizi bahan ÷ 100*. Semua kontribusi lalu dijumlahkan.\n\n## Langkah 1: Seimbangkan protein\n\nPertama-tama, hitung kebutuhan susu skim (x) dan maltodekstrin yang akan\ndipakai untuk susu ibu hamil. Jika 22 gram protein yang dikehendaki,\ndari DHA dengan kandungan 10% protein dan skim dengan kandungan 34%,\nmaka sisa malto yang dibutuhkan dapat dihitung dengan persamaan ini.\n\n$$\\underbrace{0{,}10(1)}_{\\text{DHA}} + \\underbrace{0{,}34\\,x}_{\\text{skim}} + \\underbrace{0\\,(95- x)}_{\\text{malto}} = 22$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprotein_tetap <- 0.10 * tetap[\"dha\"]              # protein dari bahan tetap\nskim  <- (target[\"protein\"] - protein_tetap) / 0.34\nmalto <- sisa - skim\n\nresep1 <- c(skim = unname(skim), malto = unname(malto), tetap)\nround(resep1, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   skim  malto    fos    dha premix \n#> 64.412 30.588  3.000  1.000  1.000\n```\n\n\n:::\n\n```{.r .cell-code}\nround(hitung_gizi(resep1), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>     air protein   lemak   karbo   serat      Ca \n#>   4.286  22.000   1.094  62.953   2.850   0.805\n```\n\n\n:::\n:::\n\n\n**Maksudnya:** protein diseimbangkan pertama karena susu skim adalah\nbahan dengan porsi terbesar dan protein adalah zat gizi utama.\nMaltodekstrin tidak mengandung protein, sehingga persamaannya jadi\nsangat sederhana.\n\nHasil *check*: skim yang dibutuhkan adalah 64.412 g dengan maltodektrin\nsebanyak 30.588 g untuk mencapai protein **22 g**. Meskipun demikian,\nlemak dan kalsium masih belum mencapai target.\n\n#### Sampingan: cek dengan Pearson Square\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkadar_perlu <- (target[\"protein\"] - protein_tetap) / sisa * 100   # % protein campuran\nbagian_skim  <- abs(kadar_perlu - 0)    # selisih dengan maltodekstrin (0%)\nbagian_malto <- abs(34 - kadar_perlu)   # selisih dengan susu skim (34%)\nc(kadar_perlu = unname(kadar_perlu),\n  skim_g  = unname(bagian_skim  / (bagian_skim + bagian_malto) * sisa),\n  malto_g = unname(bagian_malto / (bagian_skim + bagian_malto) * sisa))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> kadar_perlu      skim_g     malto_g \n#>     23.0526     64.4118     30.5882\n```\n\n\n:::\n:::\n\n\nHasilnya sama dengan langkah 1. Artinya, aljabar satu variabel dan\nPearson Square hanyalah dua cara menulis perhitungan yang sama.\n\n## Langkah 2: Seimbangkan lemak\n\nBubuk lemak (y) ditambahkan dan **maltodekstrin dikurangi** sebanyak y.\n\n$$0{,}45(1) + 0{,}01(\\text{skim}) + 0{,}70\\,y = 8$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlemak_lain <- 0.45 * tetap[\"dha\"] + 0.01 * resep1[\"skim\"]\nlemak_bubuk <- (target[\"lemak\"] - lemak_lain) / 0.70\nmalto <- resep1[\"malto\"] - lemak_bubuk\n\nresep2 <- c(skim = unname(resep1[\"skim\"]), malto = unname(malto),\n            lemak = unname(lemak_bubuk), tetap)\nround(resep2, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   skim  malto  lemak    fos    dha premix \n#> 64.412 20.723  9.866  3.000  1.000  1.000\n```\n\n\n:::\n\n```{.r .cell-code}\nround(hitung_gizi(resep2), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>     air protein   lemak   karbo   serat      Ca \n#>   3.990  22.296   8.000  55.850   2.850   0.807\n```\n\n\n:::\n:::\n\n\n**Maksudnya:** susu skim dan bubuk DHA sudah menyumbang sedikit lemak,\njadi bubuk lemak hanya perlu menutup **kekurangannya**. Perhatikan hasil\n*check*: lemak sudah tepat 8, tetapi **protein naik sedikit di atas\n22**, karena bubuk lemak juga mengandung 3% protein (dari kaseinat\npembawanya). Ini akan dikoreksi di langkah 4.\n\n## Langkah 3: Seimbangkan kalsium\n\nKalsium karbonat (z) ditambahkan dan maltodekstrin dikurangi lagi.\n\n$$0{,}0125(\\text{skim}) + 0{,}0002(\\text{bubuk lemak}) + 0{,}40\\,z = 1{,}1$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCa_lain <- 0.0125 * resep2[\"skim\"] + 0.0002 * resep2[\"lemak\"]\ncaco3 <- (target[\"Ca\"] - Ca_lain) / 0.40\nmalto <- resep2[\"malto\"] - caco3\n\nresep3 <- c(skim = unname(resep2[\"skim\"]), malto = unname(malto),\n            lemak = unname(resep2[\"lemak\"]), caco3 = unname(caco3), tetap)\nround(resep3, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   skim  malto  lemak  caco3    fos    dha premix \n#> 64.412 19.990  9.866  0.732  3.000  1.000  1.000\n```\n\n\n:::\n\n```{.r .cell-code}\nround(hitung_gizi(resep3), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>     air protein   lemak   karbo   serat      Ca \n#>  3.9533 22.2960  8.0000 55.1542  2.8500  1.1000\n```\n\n\n:::\n:::\n\n\n**Maksudnya:** kalsium diseimbangkan **terakhir** dengan bahan yang\n**hanya mengandung kalsium**. Dengan begitu, penambahan CaCO₃ tidak\nmengganggu protein dan lemak yang sudah pas. Di contoh babi, urutannya\nfosfor dulu (Dical) baru kalsium (Lime), karena Dical mengandung P\n**dan** Ca sehingga ikut menyumbang Ca. Di contoh ini tidak ada bahan\nyang menyumbang keduanya, jadi cukup satu langkah untuk mineral.\n\n## Langkah 4: Seimbangkan ulang protein\n\nSekarang jumlah bubuk lemak dan CaCO₃ sudah \"dikunci\". Protein dihitung\nulang dengan memperhitungkan protein dari bubuk lemak. Ruang untuk susu\nskim + maltodekstrin menjadi lebih kecil:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nruang <- sisa - resep3[\"lemak\"] - resep3[\"caco3\"]\nprotein_lain <- 0.10 * tetap[\"dha\"] + 0.03 * resep3[\"lemak\"]\nskim  <- (target[\"protein\"] - protein_lain) / 0.34\nmalto <- ruang - skim\n\nresep4 <- c(skim = unname(skim), malto = unname(malto),\n            lemak = unname(resep3[\"lemak\"]), caco3 = unname(resep3[\"caco3\"]), tetap)\nround(resep4, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   skim  malto  lemak  caco3    fos    dha premix \n#> 63.541 20.861  9.866  0.732  3.000  1.000  1.000\n```\n\n\n:::\n:::\n\n\n## Cek akhir: kenapa lemak dan kalsium sedikit meleset?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncek <- function(resep) {\n  hasil <- hitung_gizi(resep)[names(target)]\n  data.frame(zat_gizi = names(target), target = unname(target),\n             hasil = round(unname(hasil), 4),\n             selisih = round(unname(hasil - target), 4))\n}\ncek(resep4)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"zat_gizi\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"target\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"hasil\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"selisih\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"protein\",\"2\":\"22.0\",\"3\":\"22.0000\",\"4\":\"0.0000\"},{\"1\":\"lemak\",\"2\":\"8.0\",\"3\":\"7.9913\",\"4\":\"-0.0087\"},{\"1\":\"Ca\",\"2\":\"1.1\",\"3\":\"1.0891\",\"4\":\"-0.0109\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nDi langkah 4, susu skim **berkurang sedikit**. Susu skim juga membawa\nlemak dan kalsium, jadi lemak dan kalsium ikut turun sedikit di bawah\ntarget.\n\nIni keterbatasan metode bertahap: **setiap koreksi mengganggu zat gizi\nlain yang sudah pas**. Di buku Chiba, selisih kecil seperti ini biasanya\ndibiarkan karena masih dalam batas toleransi. Ada dua cara untuk\nmendapatkan jawaban yang tepat: mengulang langkah 1–4 sampai stabil\n(iterasi), atau menyelesaikan semuanya sekaligus sebagai sistem\npersamaan.\n\n### Cara A: iterasi (ulangi langkah sampai stabil)\n\n\n::: {.cell}\n\n```{.r .cell-code}\niterasi <- function(maks = 50, toleransi = 1e-8) {\n  lemak_b <- 0; caco3_b <- 0\n  for (i in 1:maks) {\n    # Langkah protein\n    skim <- (target[\"protein\"] - 0.10 * tetap[\"dha\"] - 0.03 * lemak_b) / 0.34\n    # Langkah lemak\n    lemak_baru <- (target[\"lemak\"] - 0.45 * tetap[\"dha\"] - 0.01 * skim) / 0.70\n    # Langkah kalsium\n    caco3_baru <- (target[\"Ca\"] - 0.0125 * skim - 0.0002 * lemak_baru) / 0.40\n    berubah <- abs(lemak_baru - lemak_b) + abs(caco3_baru - caco3_b)\n    lemak_b <- lemak_baru; caco3_b <- caco3_baru\n    if (berubah < toleransi) break\n  }\n  malto <- sisa - skim - lemak_b - caco3_b\n  list(putaran = i,\n       resep = c(skim = unname(skim), malto = unname(malto),\n                 lemak = unname(lemak_b), caco3 = unname(caco3_b), tetap))\n}\nhasil_iterasi <- iterasi()\nhasil_iterasi$putaran\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 5\n```\n\n\n:::\n\n```{.r .cell-code}\nround(hasil_iterasi$resep, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>    skim   malto   lemak   caco3     fos     dha  premix \n#> 63.5402 20.8224  9.8780  0.7594  3.0000  1.0000  1.0000\n```\n\n\n:::\n\n```{.r .cell-code}\ncek(hasil_iterasi$resep)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"zat_gizi\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"target\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"hasil\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"selisih\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"protein\",\"2\":\"22.0\",\"3\":\"22.0\",\"4\":\"0\"},{\"1\":\"lemak\",\"2\":\"8.0\",\"3\":\"8.0\",\"4\":\"0\"},{\"1\":\"Ca\",\"2\":\"1.1\",\"3\":\"1.1\",\"4\":\"0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n**Maksudnya:** langkah protein → lemak → kalsium diulang terus. Karena\npengaruh silangnya kecil, hasilnya cepat stabil dalam beberapa putaran\nsaja, dan semua target tercapai tepat.\n\n### Cara B: selesaikan sekaligus sebagai sistem persamaan linear\n\nAda 4 bahan yang belum diketahui (skim, malto, lemak, CaCO₃) dan 4\nsyarat:\n\n1.  Total keempatnya = 95 g\n2.  Protein total = 22 g\n3.  Lemak total = 8 g\n4.  Kalsium total = 1,1 g\n\nEmpat persamaan dengan empat variabel bisa diselesaikan langsung dengan\naljabar matriks (**A · x = b**):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar_bebas <- c(\"skim\", \"malto\", \"lemak\", \"caco3\")\nzat <- c(\"protein\", \"lemak\", \"Ca\")\n\nA <- rbind(total = rep(1, length(var_bebas)),\n           t(as.matrix(bahan[var_bebas, zat])) / 100)\ncolnames(A) <- var_bebas\n\nkontribusi_tetap <- hitung_gizi(tetap, kolom = zat)\nb <- c(total = sisa, target[zat] - kontribusi_tetap)\n\nA\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>           skim malto lemak caco3\n#> total   1.0000     1 1e+00   1.0\n#> protein 0.3400     0 3e-02   0.0\n#> lemak   0.0100     0 7e-01   0.0\n#> Ca      0.0125     0 2e-04   0.4\n```\n\n\n:::\n\n```{.r .cell-code}\nb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   total protein   lemak      Ca \n#>   95.00   21.90    7.55    1.10\n```\n\n\n:::\n\n```{.r .cell-code}\nsolusi <- solve(A, b)\nresep_final <- c(solusi, tetap)\nround(resep_final, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>    skim   malto   lemak   caco3     fos     dha  premix \n#> 63.5402 20.8224  9.8780  0.7594  3.0000  1.0000  1.0000\n```\n\n\n:::\n\n```{.r .cell-code}\ncek(resep_final)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"zat_gizi\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"target\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"hasil\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"selisih\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"protein\",\"2\":\"22.0\",\"3\":\"22.0\",\"4\":\"0\"},{\"1\":\"lemak\",\"2\":\"8.0\",\"3\":\"8.0\",\"4\":\"0\"},{\"1\":\"Ca\",\"2\":\"1.1\",\"3\":\"1.1\",\"4\":\"0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n**Maksudnya:** baris pertama matriks **A** adalah syarat total berat\n(koefisien 1 untuk setiap bahan). Baris berikutnya adalah kadar protein,\nlemak, dan Ca setiap bahan (dalam desimal). Vektor **b** adalah target\ndikurangi sumbangan bahan tetap. Hasilnya **sama dengan cara iterasi**.\nMetode bertahap di slide sebenarnya adalah cara manual untuk\nmenyelesaikan sistem persamaan ini. Software formulasi (seperti Excel\nSolver) dapat mengerjakan hal yang sama, dan biasanya ditambah tujuan\nuntuk meminimalkan harga (*linear programming*). Lakukan dengan Excel\nSolver pada file `formulasi_susu_ibu_hamil.xlsx` dan bandingkan\nhasilnya.\n\n## Resep akhir dan nilai gizi lengkap\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresep_tabel <- data.frame(\n  bahan = bahan[names(resep_final), \"nama\"],\n  g_per_100g = round(unname(resep_final), 2)\n)\nresep_tabel\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"bahan\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"g_per_100g\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Susu skim bubuk\",\"2\":\"63.54\"},{\"1\":\"Maltodekstrin\",\"2\":\"20.82\"},{\"1\":\"Bubuk lemak nabati (70% lemak)\",\"2\":\"9.88\"},{\"1\":\"Kalsium karbonat\",\"2\":\"0.76\"},{\"1\":\"FOS-inulin\",\"2\":\"3.00\"},{\"1\":\"Bubuk DHA (mikroenkapsulasi)\",\"2\":\"1.00\"},{\"1\":\"Premix vitamin-mineral\",\"2\":\"1.00\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nsum(resep_final)   # harus 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 100\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngizi <- hitung_gizi(resep_final)\nenergi <- 4 * gizi[\"protein\"] + 9 * gizi[\"lemak\"] + 4 * gizi[\"karbo\"] + 2 * gizi[\"serat\"]\n\ndata.frame(\n  komponen = c(\"Air (g)\", \"Protein (g)\", \"Lemak (g)\", \"Karbohidrat (g)\",\n               \"Serat FOS-inulin (g)\", \"Kalsium (mg)\", \"Energi (kkal)\"),\n  per_100g = round(c(gizi[c(\"air\", \"protein\", \"lemak\", \"karbo\", \"serat\")],\n                     gizi[\"Ca\"] * 1000, energi), 1)\n)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"komponen\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"per_100g\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Air (g)\",\"2\":\"4.0\"},{\"1\":\"Protein (g)\",\"2\":\"22.0\"},{\"1\":\"Lemak (g)\",\"2\":\"8.0\"},{\"1\":\"Karbohidrat (g)\",\"2\":\"55.5\"},{\"1\":\"Serat FOS-inulin (g)\",\"2\":\"2.9\"},{\"1\":\"Kalsium (mg)\",\"2\":\"1100.0\"},{\"1\":\"Energi (kkal)\",\"2\":\"387.7\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n**Maksudnya:** energi dihitung dengan faktor Atwater (protein dan\nkarbohidrat 4 kkal/g, lemak 9 kkal/g). FOS-inulin dihitung 2 kkal/g\nkarena hanya sebagian energinya diperoleh lewat fermentasi di usus\nbesar.\n\n### Konversi ke basis kering\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBK <- 100 - gizi[\"air\"]                  # % bahan kering formula\ngizi_bk <- gizi[c(\"protein\", \"lemak\", \"Ca\")] / (BK / 100)\nc(bahan_kering_persen = unname(BK))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> bahan_kering_persen \n#>             96.0397\n```\n\n\n:::\n\n```{.r .cell-code}\nround(rbind(basis_basah = gizi[c(\"protein\", \"lemak\", \"Ca\")],\n            basis_kering = gizi_bk), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>              protein lemak    Ca\n#> basis_basah   22.000  8.00 1.100\n#> basis_kering  22.907  8.33 1.145\n```\n\n\n:::\n:::\n\n\n**Maksudnya:** susu bubuk sangat kering (bahan kering ±96%), jadi basis\nbasah dan basis kering hanya sedikit berbeda. Inilah alasan asumsi **90%\nbahan kering** dari formulasi pakan **tidak cocok** untuk susu bubuk:\nkadar air sebaiknya diukur langsung. Sesuai *rule of thumb*, dari basis\nbasah ke basis kering **kadar zat gizi naik**.\n\n## Takaran saji\n\nMisalkan satu takaran saji adalah **45 g bubuk** (dilarutkan dalam ±200\nmL air), diminum **2 kali sehari**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaji_g <- 45\nper_saji <- c(gizi[c(\"protein\", \"lemak\", \"karbo\")] * saji_g / 100,\n              Ca_mg = unname(gizi[\"Ca\"] * 1000 * saji_g / 100),\n              energi_kkal = unname(energi * saji_g / 100))\nround(per_saji, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>     protein       lemak       karbo       Ca_mg energi_kkal \n#>         9.9         3.6        25.0       495.0       174.5\n```\n\n\n:::\n\n```{.r .cell-code}\nround(per_saji * 2, 1)   # per hari (2 saji)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>     protein       lemak       karbo       Ca_mg energi_kkal \n#>        19.8         7.2        49.9       990.0       348.9\n```\n\n\n:::\n:::\n\n\n**Maksudnya:** angka ini dibandingkan dengan **Angka Kecukupan Gizi\n(AKG) ibu hamil** untuk melihat berapa persen kebutuhan yang dipenuhi\nformula. Gunakan tabel AKG terbaru (Permenkes No. 28 Tahun 2019) sesuai\ntrimester. Formula ibu hamil dirancang sebagai **pelengkap**, bukan\nuntuk memenuhi 100% kebutuhan.\n\n## Merancang premix vitamin-mineral\n\nPremix sudah \"dipesan\" 1 g per 100 g formula. Sekarang isinya dirancang,\nmengikuti bagian *Formulating a TM or Vit premix* di buku Chiba:\ntentukan kebutuhan, perhitungkan kemurnian sumber, lalu sisanya diisi\n**bahan pembawa (*carrier*)**.\n\nTarget per 100 g formula (hipotetis):\n\n\n::: {.cell}\n\n```{.r .cell-code}\npremix_g <- tetap[\"premix\"]   # 1 g premix per 100 g formula\n\npremix <- data.frame(\n  zat      = c(\"Asam folat\", \"Besi (Fe)\", \"Seng (Zn)\", \"Yodium (I)\", \"Vitamin D3\"),\n  target   = c(400, 12, 6, 90, 400),\n  satuan   = c(\"mcg\", \"mg\", \"mg\", \"mcg\", \"IU\"),\n  sumber   = c(\"Asam folat\", \"Fero fumarat\", \"Seng sulfat monohidrat\",\n               \"Kalium iodida\", \"Vitamin D3 bubuk 100.000 IU/g\"),\n  # kadar zat dalam bahan sumber (fraksi berat, atau IU per g untuk vitamin D)\n  kadar    = c(1.00, 0.3287, 0.3643, 0.7645, 100000),\n  overage  = c(0.20, 0, 0, 0, 0.20)   # kelebihan untuk mengimbangi kehilangan selama penyimpanan\n)\n\n# ubah target ke gram zat (vitamin D tetap dalam IU)\nke_gram <- ifelse(premix$satuan == \"mcg\", 1e-6, ifelse(premix$satuan == \"mg\", 1e-3, 1))\npremix$target_x_overage <- premix$target * (1 + premix$overage)\npremix$g_sumber <- premix$target_x_overage * ke_gram / premix$kadar\n\ncarrier <- premix_g - sum(premix$g_sumber)\npremix$persen_dalam_premix <- premix$g_sumber / premix_g * 100\n\nknitr::kable(premix[, c(\"zat\", \"target\", \"satuan\", \"sumber\", \"overage\",\n                        \"g_sumber\", \"persen_dalam_premix\")], digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|zat        | target|satuan |sumber                        | overage| g_sumber| persen_dalam_premix|\n|:----------|------:|:------|:-----------------------------|-------:|--------:|-------------------:|\n|Asam folat |    400|mcg    |Asam folat                    |     0.2|   0.0005|              0.0480|\n|Besi (Fe)  |     12|mg     |Fero fumarat                  |     0.0|   0.0365|              3.6507|\n|Seng (Zn)  |      6|mg     |Seng sulfat monohidrat        |     0.0|   0.0165|              1.6470|\n|Yodium (I) |     90|mcg    |Kalium iodida                 |     0.0|   0.0001|              0.0118|\n|Vitamin D3 |    400|IU     |Vitamin D3 bubuk 100.000 IU/g |     0.2|   0.0048|              0.4800|\n\n\n:::\n\n```{.r .cell-code}\nc(carrier_maltodekstrin_g = unname(carrier),\n  carrier_persen = unname(carrier / premix_g * 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> carrier_maltodekstrin_g          carrier_persen \n#>                0.941625               94.162488\n```\n\n\n:::\n:::\n\n\n**Maksudnya:**\n\n- **Kemurnian sumber.** Kita tidak menambahkan \"besi murni\", melainkan\n  senyawa seperti fero fumarat, yang hanya mengandung ±32,9% Fe. Jadi\n  bahan sumber yang dibutuhkan = kebutuhan zat ÷ kadar zat dalam sumber.\n- ***Overage*****.** Vitamin seperti asam folat dan vitamin D bisa rusak\n  selama pengolahan dan penyimpanan, sehingga industri biasanya\n  menambahkan lebih (di sini dimisalkan 20%) agar kadar di akhir masa\n  simpan tetap memenuhi label. Mineral stabil, jadi tidak perlu\n  *overage*.\n- ***Carrier*****.** Semua bahan aktif hanya berbobot kecil, jadi\n  sisanya diisi maltodekstrin supaya premix bisa ditimbang dan dicampur\n  merata. Ini sama dengan poin \"use a carrier\" di buku.\n- Vitamin A **sengaja tidak dimasukkan** dalam bentuk retinol, karena\n  asupan retinol berlebih saat hamil berisiko teratogenik. Kalau ingin\n  ditambahkan, lebih aman dalam bentuk beta-karoten.\n\n## Latihan untuk mahasiswa\n\n1.  Ubah target protein menjadi **25 g/100 g**. Jalankan ulang semua\n    *chunk*. Bahan apa yang naik dan apa yang turun? Kenapa?\n2.  Ganti susu skim dengan **isolat protein kedelai** (misalnya protein\n    88%, lemak 1%, Ca 0,2%). Apa yang terjadi pada kebutuhan CaCO₃?\n    Jelaskan.\n3.  Hitung ulang **langkah 1** secara manual dengan Pearson Square, lalu\n    bandingkan dengan hasil R.\n4.  Tambahkan syarat baru: karbohidrat total **tidak boleh lebih dari 55\n    g/100 g**. Apakah masih bisa diselesaikan dengan 4 bahan yang ada?\n    Bahan apa yang perlu ditambahkan?\n5.  Tambahkan kolom **harga per kg** ke data bahan, lalu hitung biaya\n    bahan per kg formula. Diskusikan: bagaimana jika ingin formula\n    termurah yang tetap memenuhi semua target?\n\n## Keterbatasan pendekatan ini\n\n- Pendekatan ini hanya menjamin **angka gizi di atas kertas**. Formula\n  sungguhan juga harus mempertimbangkan kelarutan, rasa, aroma,\n  stabilitas oksidatif (terutama DHA), dan interaksi antar-zat (misalnya\n  kalsium menghambat penyerapan besi).\n- Komposisi bahan harus berasal dari **analisis laboratorium tiap lot**,\n  bukan angka tabel.\n- Batas atas zat gizi (misalnya retinol dan yodium) sama pentingnya\n  dengan batas bawah.\n- Produk akhir harus memenuhi **regulasi BPOM** untuk pangan olahan\n  keperluan gizi khusus, termasuk batas cemaran dan persyaratan label.\n\n## Rujukan\n\nChiba, L. I. (2009). *Animal Nutrition Handbook*, Section 18: Diet\nFormulation & Feed Ingredients (hlm. 481–491). Auburn University.\n",
    "supporting": [
      "formulasi_susu_ibu_hamil_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}